/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedProjectsProjectIdRouteRouteImport } from './routes/_authenticated/projects/$projectId/route'
import { Route as AuthenticatedProjectsNewIndexRouteImport } from './routes/_authenticated/projects/new/index'
import { Route as AuthenticatedProjectsProjectIdIndexRouteImport } from './routes/_authenticated/projects/$projectId/index'
import { Route as AuthenticatedProjectsProjectIdWagesIndexRouteImport } from './routes/_authenticated/projects/$projectId/wages/index'
import { Route as AuthenticatedProjectsProjectIdVendorsIndexRouteImport } from './routes/_authenticated/projects/$projectId/vendors/index'
import { Route as AuthenticatedProjectsProjectIdSubcontractorsIndexRouteImport } from './routes/_authenticated/projects/$projectId/subcontractors/index'
import { Route as AuthenticatedProjectsProjectIdPurchaseOrdersIndexRouteImport } from './routes/_authenticated/projects/$projectId/purchaseOrders/index'
import { Route as AuthenticatedProjectsProjectIdPayslipIndexRouteImport } from './routes/_authenticated/projects/$projectId/payslip/index'
import { Route as AuthenticatedProjectsProjectIdItemsIndexRouteImport } from './routes/_authenticated/projects/$projectId/items/index'
import { Route as AuthenticatedProjectsProjectIdExpensesIndexRouteImport } from './routes/_authenticated/projects/$projectId/expenses/index'
import { Route as AuthenticatedProjectsProjectIdBudgetIndexRouteImport } from './routes/_authenticated/projects/$projectId/budget/index'
import { Route as AuthenticatedProjectsProjectIdWagesNewIndexRouteImport } from './routes/_authenticated/projects/$projectId/wages/new/index'
import { Route as AuthenticatedProjectsProjectIdSubcontractorsWagesIndexRouteImport } from './routes/_authenticated/projects/$projectId/subcontractors/wages/index'
import { Route as AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersIndexRouteImport } from './routes/_authenticated/projects/$projectId/subcontractors/purchase-orders/index'
import { Route as AuthenticatedProjectsProjectIdSubcontractorsExpensesIndexRouteImport } from './routes/_authenticated/projects/$projectId/subcontractors/expenses/index'
import { Route as AuthenticatedProjectsProjectIdPurchaseOrdersNewIndexRouteImport } from './routes/_authenticated/projects/$projectId/purchaseOrders/new/index'
import { Route as AuthenticatedProjectsProjectIdExpensesNewIndexRouteImport } from './routes/_authenticated/projects/$projectId/expenses/new/index'
import { Route as AuthenticatedProjectsProjectIdEstimatesVariationsIndexRouteImport } from './routes/_authenticated/projects/$projectId/estimates/variations/index'
import { Route as AuthenticatedProjectsProjectIdEstimatesEstimateIndexRouteImport } from './routes/_authenticated/projects/$projectId/estimates/estimate/index'
import { Route as AuthenticatedProjectsProjectIdSubcontractorsWagesNewIndexRouteImport } from './routes/_authenticated/projects/$projectId/subcontractors/wages/new/index'
import { Route as AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersNewIndexRouteImport } from './routes/_authenticated/projects/$projectId/subcontractors/purchase-orders/new/index'
import { Route as AuthenticatedProjectsProjectIdSubcontractorsExpensesNewIndexRouteImport } from './routes/_authenticated/projects/$projectId/subcontractors/expenses/new/index'
import { Route as AuthenticatedProjectsProjectIdExpensesEditIdIndexRouteImport } from './routes/_authenticated/projects/$projectId/expenses/edit/$id/index'
import { Route as AuthenticatedProjectsProjectIdEstimatesVariationsNewIndexRouteImport } from './routes/_authenticated/projects/$projectId/estimates/variations/new/index'
import { Route as AuthenticatedProjectsProjectIdEstimatesEstimateNewIndexRouteImport } from './routes/_authenticated/projects/$projectId/estimates/estimate/new/index'

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdRouteRoute =
  AuthenticatedProjectsProjectIdRouteRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsNewIndexRoute =
  AuthenticatedProjectsNewIndexRouteImport.update({
    id: '/projects/new/',
    path: '/projects/new/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdIndexRoute =
  AuthenticatedProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdWagesIndexRoute =
  AuthenticatedProjectsProjectIdWagesIndexRouteImport.update({
    id: '/wages/',
    path: '/wages/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdVendorsIndexRoute =
  AuthenticatedProjectsProjectIdVendorsIndexRouteImport.update({
    id: '/vendors/',
    path: '/vendors/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdSubcontractorsIndexRoute =
  AuthenticatedProjectsProjectIdSubcontractorsIndexRouteImport.update({
    id: '/subcontractors/',
    path: '/subcontractors/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdPurchaseOrdersIndexRoute =
  AuthenticatedProjectsProjectIdPurchaseOrdersIndexRouteImport.update({
    id: '/purchaseOrders/',
    path: '/purchaseOrders/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdPayslipIndexRoute =
  AuthenticatedProjectsProjectIdPayslipIndexRouteImport.update({
    id: '/payslip/',
    path: '/payslip/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdItemsIndexRoute =
  AuthenticatedProjectsProjectIdItemsIndexRouteImport.update({
    id: '/items/',
    path: '/items/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdExpensesIndexRoute =
  AuthenticatedProjectsProjectIdExpensesIndexRouteImport.update({
    id: '/expenses/',
    path: '/expenses/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdBudgetIndexRoute =
  AuthenticatedProjectsProjectIdBudgetIndexRouteImport.update({
    id: '/budget/',
    path: '/budget/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdWagesNewIndexRoute =
  AuthenticatedProjectsProjectIdWagesNewIndexRouteImport.update({
    id: '/wages/new/',
    path: '/wages/new/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdSubcontractorsWagesIndexRoute =
  AuthenticatedProjectsProjectIdSubcontractorsWagesIndexRouteImport.update({
    id: '/subcontractors/wages/',
    path: '/subcontractors/wages/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersIndexRoute =
  AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersIndexRouteImport.update(
    {
      id: '/subcontractors/purchase-orders/',
      path: '/subcontractors/purchase-orders/',
      getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
    } as any,
  )
const AuthenticatedProjectsProjectIdSubcontractorsExpensesIndexRoute =
  AuthenticatedProjectsProjectIdSubcontractorsExpensesIndexRouteImport.update({
    id: '/subcontractors/expenses/',
    path: '/subcontractors/expenses/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdPurchaseOrdersNewIndexRoute =
  AuthenticatedProjectsProjectIdPurchaseOrdersNewIndexRouteImport.update({
    id: '/purchaseOrders/new/',
    path: '/purchaseOrders/new/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdExpensesNewIndexRoute =
  AuthenticatedProjectsProjectIdExpensesNewIndexRouteImport.update({
    id: '/expenses/new/',
    path: '/expenses/new/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdEstimatesVariationsIndexRoute =
  AuthenticatedProjectsProjectIdEstimatesVariationsIndexRouteImport.update({
    id: '/estimates/variations/',
    path: '/estimates/variations/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdEstimatesEstimateIndexRoute =
  AuthenticatedProjectsProjectIdEstimatesEstimateIndexRouteImport.update({
    id: '/estimates/estimate/',
    path: '/estimates/estimate/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdSubcontractorsWagesNewIndexRoute =
  AuthenticatedProjectsProjectIdSubcontractorsWagesNewIndexRouteImport.update({
    id: '/subcontractors/wages/new/',
    path: '/subcontractors/wages/new/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersNewIndexRoute =
  AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersNewIndexRouteImport.update(
    {
      id: '/subcontractors/purchase-orders/new/',
      path: '/subcontractors/purchase-orders/new/',
      getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
    } as any,
  )
const AuthenticatedProjectsProjectIdSubcontractorsExpensesNewIndexRoute =
  AuthenticatedProjectsProjectIdSubcontractorsExpensesNewIndexRouteImport.update(
    {
      id: '/subcontractors/expenses/new/',
      path: '/subcontractors/expenses/new/',
      getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
    } as any,
  )
const AuthenticatedProjectsProjectIdExpensesEditIdIndexRoute =
  AuthenticatedProjectsProjectIdExpensesEditIdIndexRouteImport.update({
    id: '/expenses/edit/$id/',
    path: '/expenses/edit/$id/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdEstimatesVariationsNewIndexRoute =
  AuthenticatedProjectsProjectIdEstimatesVariationsNewIndexRouteImport.update({
    id: '/estimates/variations/new/',
    path: '/estimates/variations/new/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdEstimatesEstimateNewIndexRoute =
  AuthenticatedProjectsProjectIdEstimatesEstimateNewIndexRouteImport.update({
    id: '/estimates/estimate/new/',
    path: '/estimates/estimate/new/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/': typeof ClerkauthRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteRouteWithChildren
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/projects/new': typeof AuthenticatedProjectsNewIndexRoute
  '/projects/$projectId/budget': typeof AuthenticatedProjectsProjectIdBudgetIndexRoute
  '/projects/$projectId/expenses': typeof AuthenticatedProjectsProjectIdExpensesIndexRoute
  '/projects/$projectId/items': typeof AuthenticatedProjectsProjectIdItemsIndexRoute
  '/projects/$projectId/payslip': typeof AuthenticatedProjectsProjectIdPayslipIndexRoute
  '/projects/$projectId/purchaseOrders': typeof AuthenticatedProjectsProjectIdPurchaseOrdersIndexRoute
  '/projects/$projectId/subcontractors': typeof AuthenticatedProjectsProjectIdSubcontractorsIndexRoute
  '/projects/$projectId/vendors': typeof AuthenticatedProjectsProjectIdVendorsIndexRoute
  '/projects/$projectId/wages': typeof AuthenticatedProjectsProjectIdWagesIndexRoute
  '/projects/$projectId/estimates/estimate': typeof AuthenticatedProjectsProjectIdEstimatesEstimateIndexRoute
  '/projects/$projectId/estimates/variations': typeof AuthenticatedProjectsProjectIdEstimatesVariationsIndexRoute
  '/projects/$projectId/expenses/new': typeof AuthenticatedProjectsProjectIdExpensesNewIndexRoute
  '/projects/$projectId/purchaseOrders/new': typeof AuthenticatedProjectsProjectIdPurchaseOrdersNewIndexRoute
  '/projects/$projectId/subcontractors/expenses': typeof AuthenticatedProjectsProjectIdSubcontractorsExpensesIndexRoute
  '/projects/$projectId/subcontractors/purchase-orders': typeof AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersIndexRoute
  '/projects/$projectId/subcontractors/wages': typeof AuthenticatedProjectsProjectIdSubcontractorsWagesIndexRoute
  '/projects/$projectId/wages/new': typeof AuthenticatedProjectsProjectIdWagesNewIndexRoute
  '/projects/$projectId/estimates/estimate/new': typeof AuthenticatedProjectsProjectIdEstimatesEstimateNewIndexRoute
  '/projects/$projectId/estimates/variations/new': typeof AuthenticatedProjectsProjectIdEstimatesVariationsNewIndexRoute
  '/projects/$projectId/expenses/edit/$id': typeof AuthenticatedProjectsProjectIdExpensesEditIdIndexRoute
  '/projects/$projectId/subcontractors/expenses/new': typeof AuthenticatedProjectsProjectIdSubcontractorsExpensesNewIndexRoute
  '/projects/$projectId/subcontractors/purchase-orders/new': typeof AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersNewIndexRoute
  '/projects/$projectId/subcontractors/wages/new': typeof AuthenticatedProjectsProjectIdSubcontractorsWagesNewIndexRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/projects/new': typeof AuthenticatedProjectsNewIndexRoute
  '/projects/$projectId/budget': typeof AuthenticatedProjectsProjectIdBudgetIndexRoute
  '/projects/$projectId/expenses': typeof AuthenticatedProjectsProjectIdExpensesIndexRoute
  '/projects/$projectId/items': typeof AuthenticatedProjectsProjectIdItemsIndexRoute
  '/projects/$projectId/payslip': typeof AuthenticatedProjectsProjectIdPayslipIndexRoute
  '/projects/$projectId/purchaseOrders': typeof AuthenticatedProjectsProjectIdPurchaseOrdersIndexRoute
  '/projects/$projectId/subcontractors': typeof AuthenticatedProjectsProjectIdSubcontractorsIndexRoute
  '/projects/$projectId/vendors': typeof AuthenticatedProjectsProjectIdVendorsIndexRoute
  '/projects/$projectId/wages': typeof AuthenticatedProjectsProjectIdWagesIndexRoute
  '/projects/$projectId/estimates/estimate': typeof AuthenticatedProjectsProjectIdEstimatesEstimateIndexRoute
  '/projects/$projectId/estimates/variations': typeof AuthenticatedProjectsProjectIdEstimatesVariationsIndexRoute
  '/projects/$projectId/expenses/new': typeof AuthenticatedProjectsProjectIdExpensesNewIndexRoute
  '/projects/$projectId/purchaseOrders/new': typeof AuthenticatedProjectsProjectIdPurchaseOrdersNewIndexRoute
  '/projects/$projectId/subcontractors/expenses': typeof AuthenticatedProjectsProjectIdSubcontractorsExpensesIndexRoute
  '/projects/$projectId/subcontractors/purchase-orders': typeof AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersIndexRoute
  '/projects/$projectId/subcontractors/wages': typeof AuthenticatedProjectsProjectIdSubcontractorsWagesIndexRoute
  '/projects/$projectId/wages/new': typeof AuthenticatedProjectsProjectIdWagesNewIndexRoute
  '/projects/$projectId/estimates/estimate/new': typeof AuthenticatedProjectsProjectIdEstimatesEstimateNewIndexRoute
  '/projects/$projectId/estimates/variations/new': typeof AuthenticatedProjectsProjectIdEstimatesVariationsNewIndexRoute
  '/projects/$projectId/expenses/edit/$id': typeof AuthenticatedProjectsProjectIdExpensesEditIdIndexRoute
  '/projects/$projectId/subcontractors/expenses/new': typeof AuthenticatedProjectsProjectIdSubcontractorsExpensesNewIndexRoute
  '/projects/$projectId/subcontractors/purchase-orders/new': typeof AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersNewIndexRoute
  '/projects/$projectId/subcontractors/wages/new': typeof AuthenticatedProjectsProjectIdSubcontractorsWagesNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteRouteWithChildren
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/_authenticated/projects/new/': typeof AuthenticatedProjectsNewIndexRoute
  '/_authenticated/projects/$projectId/budget/': typeof AuthenticatedProjectsProjectIdBudgetIndexRoute
  '/_authenticated/projects/$projectId/expenses/': typeof AuthenticatedProjectsProjectIdExpensesIndexRoute
  '/_authenticated/projects/$projectId/items/': typeof AuthenticatedProjectsProjectIdItemsIndexRoute
  '/_authenticated/projects/$projectId/payslip/': typeof AuthenticatedProjectsProjectIdPayslipIndexRoute
  '/_authenticated/projects/$projectId/purchaseOrders/': typeof AuthenticatedProjectsProjectIdPurchaseOrdersIndexRoute
  '/_authenticated/projects/$projectId/subcontractors/': typeof AuthenticatedProjectsProjectIdSubcontractorsIndexRoute
  '/_authenticated/projects/$projectId/vendors/': typeof AuthenticatedProjectsProjectIdVendorsIndexRoute
  '/_authenticated/projects/$projectId/wages/': typeof AuthenticatedProjectsProjectIdWagesIndexRoute
  '/_authenticated/projects/$projectId/estimates/estimate/': typeof AuthenticatedProjectsProjectIdEstimatesEstimateIndexRoute
  '/_authenticated/projects/$projectId/estimates/variations/': typeof AuthenticatedProjectsProjectIdEstimatesVariationsIndexRoute
  '/_authenticated/projects/$projectId/expenses/new/': typeof AuthenticatedProjectsProjectIdExpensesNewIndexRoute
  '/_authenticated/projects/$projectId/purchaseOrders/new/': typeof AuthenticatedProjectsProjectIdPurchaseOrdersNewIndexRoute
  '/_authenticated/projects/$projectId/subcontractors/expenses/': typeof AuthenticatedProjectsProjectIdSubcontractorsExpensesIndexRoute
  '/_authenticated/projects/$projectId/subcontractors/purchase-orders/': typeof AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersIndexRoute
  '/_authenticated/projects/$projectId/subcontractors/wages/': typeof AuthenticatedProjectsProjectIdSubcontractorsWagesIndexRoute
  '/_authenticated/projects/$projectId/wages/new/': typeof AuthenticatedProjectsProjectIdWagesNewIndexRoute
  '/_authenticated/projects/$projectId/estimates/estimate/new/': typeof AuthenticatedProjectsProjectIdEstimatesEstimateNewIndexRoute
  '/_authenticated/projects/$projectId/estimates/variations/new/': typeof AuthenticatedProjectsProjectIdEstimatesVariationsNewIndexRoute
  '/_authenticated/projects/$projectId/expenses/edit/$id/': typeof AuthenticatedProjectsProjectIdExpensesEditIdIndexRoute
  '/_authenticated/projects/$projectId/subcontractors/expenses/new/': typeof AuthenticatedProjectsProjectIdSubcontractorsExpensesNewIndexRoute
  '/_authenticated/projects/$projectId/subcontractors/purchase-orders/new/': typeof AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersNewIndexRoute
  '/_authenticated/projects/$projectId/subcontractors/wages/new/': typeof AuthenticatedProjectsProjectIdSubcontractorsWagesNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/clerk'
    | '/settings'
    | '/clerk/'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/projects/$projectId'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/settings/'
    | '/tasks'
    | '/users'
    | '/projects/$projectId/'
    | '/projects/new'
    | '/projects/$projectId/budget'
    | '/projects/$projectId/expenses'
    | '/projects/$projectId/items'
    | '/projects/$projectId/payslip'
    | '/projects/$projectId/purchaseOrders'
    | '/projects/$projectId/subcontractors'
    | '/projects/$projectId/vendors'
    | '/projects/$projectId/wages'
    | '/projects/$projectId/estimates/estimate'
    | '/projects/$projectId/estimates/variations'
    | '/projects/$projectId/expenses/new'
    | '/projects/$projectId/purchaseOrders/new'
    | '/projects/$projectId/subcontractors/expenses'
    | '/projects/$projectId/subcontractors/purchase-orders'
    | '/projects/$projectId/subcontractors/wages'
    | '/projects/$projectId/wages/new'
    | '/projects/$projectId/estimates/estimate/new'
    | '/projects/$projectId/estimates/variations/new'
    | '/projects/$projectId/expenses/edit/$id'
    | '/projects/$projectId/subcontractors/expenses/new'
    | '/projects/$projectId/subcontractors/purchase-orders/new'
    | '/projects/$projectId/subcontractors/wages/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/projects/$projectId'
    | '/projects/new'
    | '/projects/$projectId/budget'
    | '/projects/$projectId/expenses'
    | '/projects/$projectId/items'
    | '/projects/$projectId/payslip'
    | '/projects/$projectId/purchaseOrders'
    | '/projects/$projectId/subcontractors'
    | '/projects/$projectId/vendors'
    | '/projects/$projectId/wages'
    | '/projects/$projectId/estimates/estimate'
    | '/projects/$projectId/estimates/variations'
    | '/projects/$projectId/expenses/new'
    | '/projects/$projectId/purchaseOrders/new'
    | '/projects/$projectId/subcontractors/expenses'
    | '/projects/$projectId/subcontractors/purchase-orders'
    | '/projects/$projectId/subcontractors/wages'
    | '/projects/$projectId/wages/new'
    | '/projects/$projectId/estimates/estimate/new'
    | '/projects/$projectId/estimates/variations/new'
    | '/projects/$projectId/expenses/edit/$id'
    | '/projects/$projectId/subcontractors/expenses/new'
    | '/projects/$projectId/subcontractors/purchase-orders/new'
    | '/projects/$projectId/subcontractors/wages/new'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/help-center/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/projects/$projectId/'
    | '/_authenticated/projects/new/'
    | '/_authenticated/projects/$projectId/budget/'
    | '/_authenticated/projects/$projectId/expenses/'
    | '/_authenticated/projects/$projectId/items/'
    | '/_authenticated/projects/$projectId/payslip/'
    | '/_authenticated/projects/$projectId/purchaseOrders/'
    | '/_authenticated/projects/$projectId/subcontractors/'
    | '/_authenticated/projects/$projectId/vendors/'
    | '/_authenticated/projects/$projectId/wages/'
    | '/_authenticated/projects/$projectId/estimates/estimate/'
    | '/_authenticated/projects/$projectId/estimates/variations/'
    | '/_authenticated/projects/$projectId/expenses/new/'
    | '/_authenticated/projects/$projectId/purchaseOrders/new/'
    | '/_authenticated/projects/$projectId/subcontractors/expenses/'
    | '/_authenticated/projects/$projectId/subcontractors/purchase-orders/'
    | '/_authenticated/projects/$projectId/subcontractors/wages/'
    | '/_authenticated/projects/$projectId/wages/new/'
    | '/_authenticated/projects/$projectId/estimates/estimate/new/'
    | '/_authenticated/projects/$projectId/estimates/variations/new/'
    | '/_authenticated/projects/$projectId/expenses/edit/$id/'
    | '/_authenticated/projects/$projectId/subcontractors/expenses/new/'
    | '/_authenticated/projects/$projectId/subcontractors/purchase-orders/new/'
    | '/_authenticated/projects/$projectId/subcontractors/wages/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: '/'
      fullPath: '/clerk/'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/new/': {
      id: '/_authenticated/projects/new/'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthenticatedProjectsNewIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/': {
      id: '/_authenticated/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/wages/': {
      id: '/_authenticated/projects/$projectId/wages/'
      path: '/wages'
      fullPath: '/projects/$projectId/wages'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdWagesIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/vendors/': {
      id: '/_authenticated/projects/$projectId/vendors/'
      path: '/vendors'
      fullPath: '/projects/$projectId/vendors'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdVendorsIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/subcontractors/': {
      id: '/_authenticated/projects/$projectId/subcontractors/'
      path: '/subcontractors'
      fullPath: '/projects/$projectId/subcontractors'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSubcontractorsIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/purchaseOrders/': {
      id: '/_authenticated/projects/$projectId/purchaseOrders/'
      path: '/purchaseOrders'
      fullPath: '/projects/$projectId/purchaseOrders'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdPurchaseOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/payslip/': {
      id: '/_authenticated/projects/$projectId/payslip/'
      path: '/payslip'
      fullPath: '/projects/$projectId/payslip'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdPayslipIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/items/': {
      id: '/_authenticated/projects/$projectId/items/'
      path: '/items'
      fullPath: '/projects/$projectId/items'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdItemsIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/expenses/': {
      id: '/_authenticated/projects/$projectId/expenses/'
      path: '/expenses'
      fullPath: '/projects/$projectId/expenses'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdExpensesIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/budget/': {
      id: '/_authenticated/projects/$projectId/budget/'
      path: '/budget'
      fullPath: '/projects/$projectId/budget'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdBudgetIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/wages/new/': {
      id: '/_authenticated/projects/$projectId/wages/new/'
      path: '/wages/new'
      fullPath: '/projects/$projectId/wages/new'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdWagesNewIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/subcontractors/wages/': {
      id: '/_authenticated/projects/$projectId/subcontractors/wages/'
      path: '/subcontractors/wages'
      fullPath: '/projects/$projectId/subcontractors/wages'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSubcontractorsWagesIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/subcontractors/purchase-orders/': {
      id: '/_authenticated/projects/$projectId/subcontractors/purchase-orders/'
      path: '/subcontractors/purchase-orders'
      fullPath: '/projects/$projectId/subcontractors/purchase-orders'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/subcontractors/expenses/': {
      id: '/_authenticated/projects/$projectId/subcontractors/expenses/'
      path: '/subcontractors/expenses'
      fullPath: '/projects/$projectId/subcontractors/expenses'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSubcontractorsExpensesIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/purchaseOrders/new/': {
      id: '/_authenticated/projects/$projectId/purchaseOrders/new/'
      path: '/purchaseOrders/new'
      fullPath: '/projects/$projectId/purchaseOrders/new'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdPurchaseOrdersNewIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/expenses/new/': {
      id: '/_authenticated/projects/$projectId/expenses/new/'
      path: '/expenses/new'
      fullPath: '/projects/$projectId/expenses/new'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdExpensesNewIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/estimates/variations/': {
      id: '/_authenticated/projects/$projectId/estimates/variations/'
      path: '/estimates/variations'
      fullPath: '/projects/$projectId/estimates/variations'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdEstimatesVariationsIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/estimates/estimate/': {
      id: '/_authenticated/projects/$projectId/estimates/estimate/'
      path: '/estimates/estimate'
      fullPath: '/projects/$projectId/estimates/estimate'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdEstimatesEstimateIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/subcontractors/wages/new/': {
      id: '/_authenticated/projects/$projectId/subcontractors/wages/new/'
      path: '/subcontractors/wages/new'
      fullPath: '/projects/$projectId/subcontractors/wages/new'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSubcontractorsWagesNewIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/subcontractors/purchase-orders/new/': {
      id: '/_authenticated/projects/$projectId/subcontractors/purchase-orders/new/'
      path: '/subcontractors/purchase-orders/new'
      fullPath: '/projects/$projectId/subcontractors/purchase-orders/new'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersNewIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/subcontractors/expenses/new/': {
      id: '/_authenticated/projects/$projectId/subcontractors/expenses/new/'
      path: '/subcontractors/expenses/new'
      fullPath: '/projects/$projectId/subcontractors/expenses/new'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSubcontractorsExpensesNewIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/expenses/edit/$id/': {
      id: '/_authenticated/projects/$projectId/expenses/edit/$id/'
      path: '/expenses/edit/$id'
      fullPath: '/projects/$projectId/expenses/edit/$id'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdExpensesEditIdIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/estimates/variations/new/': {
      id: '/_authenticated/projects/$projectId/estimates/variations/new/'
      path: '/estimates/variations/new'
      fullPath: '/projects/$projectId/estimates/variations/new'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdEstimatesVariationsNewIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/estimates/estimate/new/': {
      id: '/_authenticated/projects/$projectId/estimates/estimate/new/'
      path: '/estimates/estimate/new'
      fullPath: '/projects/$projectId/estimates/estimate/new'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdEstimatesEstimateNewIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedProjectsProjectIdRouteRouteChildren {
  AuthenticatedProjectsProjectIdIndexRoute: typeof AuthenticatedProjectsProjectIdIndexRoute
  AuthenticatedProjectsProjectIdBudgetIndexRoute: typeof AuthenticatedProjectsProjectIdBudgetIndexRoute
  AuthenticatedProjectsProjectIdExpensesIndexRoute: typeof AuthenticatedProjectsProjectIdExpensesIndexRoute
  AuthenticatedProjectsProjectIdItemsIndexRoute: typeof AuthenticatedProjectsProjectIdItemsIndexRoute
  AuthenticatedProjectsProjectIdPayslipIndexRoute: typeof AuthenticatedProjectsProjectIdPayslipIndexRoute
  AuthenticatedProjectsProjectIdPurchaseOrdersIndexRoute: typeof AuthenticatedProjectsProjectIdPurchaseOrdersIndexRoute
  AuthenticatedProjectsProjectIdSubcontractorsIndexRoute: typeof AuthenticatedProjectsProjectIdSubcontractorsIndexRoute
  AuthenticatedProjectsProjectIdVendorsIndexRoute: typeof AuthenticatedProjectsProjectIdVendorsIndexRoute
  AuthenticatedProjectsProjectIdWagesIndexRoute: typeof AuthenticatedProjectsProjectIdWagesIndexRoute
  AuthenticatedProjectsProjectIdEstimatesEstimateIndexRoute: typeof AuthenticatedProjectsProjectIdEstimatesEstimateIndexRoute
  AuthenticatedProjectsProjectIdEstimatesVariationsIndexRoute: typeof AuthenticatedProjectsProjectIdEstimatesVariationsIndexRoute
  AuthenticatedProjectsProjectIdExpensesNewIndexRoute: typeof AuthenticatedProjectsProjectIdExpensesNewIndexRoute
  AuthenticatedProjectsProjectIdPurchaseOrdersNewIndexRoute: typeof AuthenticatedProjectsProjectIdPurchaseOrdersNewIndexRoute
  AuthenticatedProjectsProjectIdSubcontractorsExpensesIndexRoute: typeof AuthenticatedProjectsProjectIdSubcontractorsExpensesIndexRoute
  AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersIndexRoute: typeof AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersIndexRoute
  AuthenticatedProjectsProjectIdSubcontractorsWagesIndexRoute: typeof AuthenticatedProjectsProjectIdSubcontractorsWagesIndexRoute
  AuthenticatedProjectsProjectIdWagesNewIndexRoute: typeof AuthenticatedProjectsProjectIdWagesNewIndexRoute
  AuthenticatedProjectsProjectIdEstimatesEstimateNewIndexRoute: typeof AuthenticatedProjectsProjectIdEstimatesEstimateNewIndexRoute
  AuthenticatedProjectsProjectIdEstimatesVariationsNewIndexRoute: typeof AuthenticatedProjectsProjectIdEstimatesVariationsNewIndexRoute
  AuthenticatedProjectsProjectIdExpensesEditIdIndexRoute: typeof AuthenticatedProjectsProjectIdExpensesEditIdIndexRoute
  AuthenticatedProjectsProjectIdSubcontractorsExpensesNewIndexRoute: typeof AuthenticatedProjectsProjectIdSubcontractorsExpensesNewIndexRoute
  AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersNewIndexRoute: typeof AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersNewIndexRoute
  AuthenticatedProjectsProjectIdSubcontractorsWagesNewIndexRoute: typeof AuthenticatedProjectsProjectIdSubcontractorsWagesNewIndexRoute
}

const AuthenticatedProjectsProjectIdRouteRouteChildren: AuthenticatedProjectsProjectIdRouteRouteChildren =
  {
    AuthenticatedProjectsProjectIdIndexRoute:
      AuthenticatedProjectsProjectIdIndexRoute,
    AuthenticatedProjectsProjectIdBudgetIndexRoute:
      AuthenticatedProjectsProjectIdBudgetIndexRoute,
    AuthenticatedProjectsProjectIdExpensesIndexRoute:
      AuthenticatedProjectsProjectIdExpensesIndexRoute,
    AuthenticatedProjectsProjectIdItemsIndexRoute:
      AuthenticatedProjectsProjectIdItemsIndexRoute,
    AuthenticatedProjectsProjectIdPayslipIndexRoute:
      AuthenticatedProjectsProjectIdPayslipIndexRoute,
    AuthenticatedProjectsProjectIdPurchaseOrdersIndexRoute:
      AuthenticatedProjectsProjectIdPurchaseOrdersIndexRoute,
    AuthenticatedProjectsProjectIdSubcontractorsIndexRoute:
      AuthenticatedProjectsProjectIdSubcontractorsIndexRoute,
    AuthenticatedProjectsProjectIdVendorsIndexRoute:
      AuthenticatedProjectsProjectIdVendorsIndexRoute,
    AuthenticatedProjectsProjectIdWagesIndexRoute:
      AuthenticatedProjectsProjectIdWagesIndexRoute,
    AuthenticatedProjectsProjectIdEstimatesEstimateIndexRoute:
      AuthenticatedProjectsProjectIdEstimatesEstimateIndexRoute,
    AuthenticatedProjectsProjectIdEstimatesVariationsIndexRoute:
      AuthenticatedProjectsProjectIdEstimatesVariationsIndexRoute,
    AuthenticatedProjectsProjectIdExpensesNewIndexRoute:
      AuthenticatedProjectsProjectIdExpensesNewIndexRoute,
    AuthenticatedProjectsProjectIdPurchaseOrdersNewIndexRoute:
      AuthenticatedProjectsProjectIdPurchaseOrdersNewIndexRoute,
    AuthenticatedProjectsProjectIdSubcontractorsExpensesIndexRoute:
      AuthenticatedProjectsProjectIdSubcontractorsExpensesIndexRoute,
    AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersIndexRoute:
      AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersIndexRoute,
    AuthenticatedProjectsProjectIdSubcontractorsWagesIndexRoute:
      AuthenticatedProjectsProjectIdSubcontractorsWagesIndexRoute,
    AuthenticatedProjectsProjectIdWagesNewIndexRoute:
      AuthenticatedProjectsProjectIdWagesNewIndexRoute,
    AuthenticatedProjectsProjectIdEstimatesEstimateNewIndexRoute:
      AuthenticatedProjectsProjectIdEstimatesEstimateNewIndexRoute,
    AuthenticatedProjectsProjectIdEstimatesVariationsNewIndexRoute:
      AuthenticatedProjectsProjectIdEstimatesVariationsNewIndexRoute,
    AuthenticatedProjectsProjectIdExpensesEditIdIndexRoute:
      AuthenticatedProjectsProjectIdExpensesEditIdIndexRoute,
    AuthenticatedProjectsProjectIdSubcontractorsExpensesNewIndexRoute:
      AuthenticatedProjectsProjectIdSubcontractorsExpensesNewIndexRoute,
    AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersNewIndexRoute:
      AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersNewIndexRoute,
    AuthenticatedProjectsProjectIdSubcontractorsWagesNewIndexRoute:
      AuthenticatedProjectsProjectIdSubcontractorsWagesNewIndexRoute,
  }

const AuthenticatedProjectsProjectIdRouteRouteWithChildren =
  AuthenticatedProjectsProjectIdRouteRoute._addFileChildren(
    AuthenticatedProjectsProjectIdRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedProjectsProjectIdRouteRoute: typeof AuthenticatedProjectsProjectIdRouteRouteWithChildren
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedProjectsNewIndexRoute: typeof AuthenticatedProjectsNewIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProjectsProjectIdRouteRoute:
    AuthenticatedProjectsProjectIdRouteRouteWithChildren,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedProjectsNewIndexRoute: AuthenticatedProjectsNewIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
