/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedVendorsIndexRouteImport } from './routes/_authenticated/vendors/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedItemsIndexRouteImport } from './routes/_authenticated/items/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedSubcontractorsIndexRouteImport } from './routes/_authenticated/Subcontractors/index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/Clients/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedProjectsProjectIdRouteRouteImport } from './routes/_authenticated/projects/$projectId/route'
import { Route as AuthenticatedVendorsNewIndexRouteImport } from './routes/_authenticated/vendors/new/index'
import { Route as AuthenticatedUsersUserIdIndexRouteImport } from './routes/_authenticated/users/$userId/index'
import { Route as AuthenticatedProjectsNewIndexRouteImport } from './routes/_authenticated/projects/new/index'
import { Route as AuthenticatedProjectsProjectIdIndexRouteImport } from './routes/_authenticated/projects/$projectId/index'
import { Route as AuthenticatedProjectsProjectIdWagesIndexRouteImport } from './routes/_authenticated/projects/$projectId/wages/index'
import { Route as AuthenticatedProjectsProjectIdPurchaseOrdersIndexRouteImport } from './routes/_authenticated/projects/$projectId/purchaseOrders/index'
import { Route as AuthenticatedProjectsProjectIdPayslipIndexRouteImport } from './routes/_authenticated/projects/$projectId/payslip/index'
import { Route as AuthenticatedProjectsProjectIdExpensesIndexRouteImport } from './routes/_authenticated/projects/$projectId/expenses/index'
import { Route as AuthenticatedProjectsProjectIdEditIndexRouteImport } from './routes/_authenticated/projects/$projectId/edit/index'
import { Route as AuthenticatedProjectsProjectIdBudgetIndexRouteImport } from './routes/_authenticated/projects/$projectId/budget/index'
import { Route as AuthenticatedProjectsProjectIdWagesNewIndexRouteImport } from './routes/_authenticated/projects/$projectId/wages/new/index'
import { Route as AuthenticatedProjectsProjectIdWagesWageIdIndexRouteImport } from './routes/_authenticated/projects/$projectId/wages/$WageId/index'
import { Route as AuthenticatedProjectsProjectIdSubcontractorsWagesIndexRouteImport } from './routes/_authenticated/projects/$projectId/subcontractors/wages/index'
import { Route as AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersIndexRouteImport } from './routes/_authenticated/projects/$projectId/subcontractors/purchase-orders/index'
import { Route as AuthenticatedProjectsProjectIdSubcontractorsExpensesIndexRouteImport } from './routes/_authenticated/projects/$projectId/subcontractors/expenses/index'
import { Route as AuthenticatedProjectsProjectIdPurchaseOrdersNewIndexRouteImport } from './routes/_authenticated/projects/$projectId/purchaseOrders/new/index'
import { Route as AuthenticatedProjectsProjectIdPurchaseOrdersPurchaseIdIndexRouteImport } from './routes/_authenticated/projects/$projectId/purchaseOrders/$purchaseId/index'
import { Route as AuthenticatedProjectsProjectIdPayslipNewIndexRouteImport } from './routes/_authenticated/projects/$projectId/payslip/new/index'
import { Route as AuthenticatedProjectsProjectIdPayslipPayslipIdIndexRouteImport } from './routes/_authenticated/projects/$projectId/payslip/$PayslipId/index'
import { Route as AuthenticatedProjectsProjectIdExpensesNewIndexRouteImport } from './routes/_authenticated/projects/$projectId/expenses/new/index'
import { Route as AuthenticatedProjectsProjectIdExpensesExpenseIdIndexRouteImport } from './routes/_authenticated/projects/$projectId/expenses/$ExpenseId/index'
import { Route as AuthenticatedProjectsProjectIdEstimatesVariationsIndexRouteImport } from './routes/_authenticated/projects/$projectId/estimates/variations/index'
import { Route as AuthenticatedProjectsProjectIdEstimatesEstimateIndexRouteImport } from './routes/_authenticated/projects/$projectId/estimates/estimate/index'
import { Route as AuthenticatedProjectsProjectIdWagesWageIdEditIndexRouteImport } from './routes/_authenticated/projects/$projectId/wages/$WageId/edit/index'
import { Route as AuthenticatedProjectsProjectIdSubcontractorsWagesNewIndexRouteImport } from './routes/_authenticated/projects/$projectId/subcontractors/wages/new/index'
import { Route as AuthenticatedProjectsProjectIdSubcontractorsWagesWageIdIndexRouteImport } from './routes/_authenticated/projects/$projectId/subcontractors/wages/$wageId/index'
import { Route as AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersNewIndexRouteImport } from './routes/_authenticated/projects/$projectId/subcontractors/purchase-orders/new/index'
import { Route as AuthenticatedProjectsProjectIdSubcontractorsExpensesNewIndexRouteImport } from './routes/_authenticated/projects/$projectId/subcontractors/expenses/new/index'
import { Route as AuthenticatedProjectsProjectIdSubcontractorsExpensesExpenseIdIndexRouteImport } from './routes/_authenticated/projects/$projectId/subcontractors/expenses/$expenseId/index'
import { Route as AuthenticatedProjectsProjectIdPurchaseOrdersPurchaseIdEditIndexRouteImport } from './routes/_authenticated/projects/$projectId/purchaseOrders/$purchaseId/edit/index'
import { Route as AuthenticatedProjectsProjectIdPayslipPayslipIdEditIndexRouteImport } from './routes/_authenticated/projects/$projectId/payslip/$PayslipId/edit/index'
import { Route as AuthenticatedProjectsProjectIdExpensesExpenseIdEditIndexRouteImport } from './routes/_authenticated/projects/$projectId/expenses/$ExpenseId/edit/index'
import { Route as AuthenticatedProjectsProjectIdEstimatesVariationsNewIndexRouteImport } from './routes/_authenticated/projects/$projectId/estimates/variations/new/index'
import { Route as AuthenticatedProjectsProjectIdEstimatesVariationsVariationIdIndexRouteImport } from './routes/_authenticated/projects/$projectId/estimates/variations/$variationId/index'
import { Route as AuthenticatedProjectsProjectIdEstimatesEstimateNewIndexRouteImport } from './routes/_authenticated/projects/$projectId/estimates/estimate/new/index'
import { Route as AuthenticatedProjectsProjectIdSubcontractorsWagesWageIdEditIndexRouteImport } from './routes/_authenticated/projects/$projectId/subcontractors/wages/$wageId/edit/index'
import { Route as AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersPurchaseIdEditIndexRouteImport } from './routes/_authenticated/projects/$projectId/subcontractors/purchase-orders/$purchaseId/edit/index'
import { Route as AuthenticatedProjectsProjectIdSubcontractorsExpensesExpenseIdEditIndexRouteImport } from './routes/_authenticated/projects/$projectId/subcontractors/expenses/$expenseId/edit/index'
import { Route as AuthenticatedProjectsProjectIdEstimatesVariationsVariationIdEditIndexRouteImport } from './routes/_authenticated/projects/$projectId/estimates/variations/$variationId/edit/index'

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorsIndexRoute =
  AuthenticatedVendorsIndexRouteImport.update({
    id: '/vendors/',
    path: '/vendors/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedItemsIndexRoute = AuthenticatedItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubcontractorsIndexRoute =
  AuthenticatedSubcontractorsIndexRouteImport.update({
    id: '/Subcontractors/',
    path: '/Subcontractors/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/Clients/',
    path: '/Clients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdRouteRoute =
  AuthenticatedProjectsProjectIdRouteRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorsNewIndexRoute =
  AuthenticatedVendorsNewIndexRouteImport.update({
    id: '/vendors/new/',
    path: '/vendors/new/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersUserIdIndexRoute =
  AuthenticatedUsersUserIdIndexRouteImport.update({
    id: '/users/$userId/',
    path: '/users/$userId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsNewIndexRoute =
  AuthenticatedProjectsNewIndexRouteImport.update({
    id: '/projects/new/',
    path: '/projects/new/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdIndexRoute =
  AuthenticatedProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdWagesIndexRoute =
  AuthenticatedProjectsProjectIdWagesIndexRouteImport.update({
    id: '/wages/',
    path: '/wages/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdPurchaseOrdersIndexRoute =
  AuthenticatedProjectsProjectIdPurchaseOrdersIndexRouteImport.update({
    id: '/purchaseOrders/',
    path: '/purchaseOrders/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdPayslipIndexRoute =
  AuthenticatedProjectsProjectIdPayslipIndexRouteImport.update({
    id: '/payslip/',
    path: '/payslip/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdExpensesIndexRoute =
  AuthenticatedProjectsProjectIdExpensesIndexRouteImport.update({
    id: '/expenses/',
    path: '/expenses/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdEditIndexRoute =
  AuthenticatedProjectsProjectIdEditIndexRouteImport.update({
    id: '/edit/',
    path: '/edit/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdBudgetIndexRoute =
  AuthenticatedProjectsProjectIdBudgetIndexRouteImport.update({
    id: '/budget/',
    path: '/budget/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdWagesNewIndexRoute =
  AuthenticatedProjectsProjectIdWagesNewIndexRouteImport.update({
    id: '/wages/new/',
    path: '/wages/new/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdWagesWageIdIndexRoute =
  AuthenticatedProjectsProjectIdWagesWageIdIndexRouteImport.update({
    id: '/wages/$WageId/',
    path: '/wages/$WageId/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdSubcontractorsWagesIndexRoute =
  AuthenticatedProjectsProjectIdSubcontractorsWagesIndexRouteImport.update({
    id: '/subcontractors/wages/',
    path: '/subcontractors/wages/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersIndexRoute =
  AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersIndexRouteImport.update(
    {
      id: '/subcontractors/purchase-orders/',
      path: '/subcontractors/purchase-orders/',
      getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
    } as any,
  )
const AuthenticatedProjectsProjectIdSubcontractorsExpensesIndexRoute =
  AuthenticatedProjectsProjectIdSubcontractorsExpensesIndexRouteImport.update({
    id: '/subcontractors/expenses/',
    path: '/subcontractors/expenses/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdPurchaseOrdersNewIndexRoute =
  AuthenticatedProjectsProjectIdPurchaseOrdersNewIndexRouteImport.update({
    id: '/purchaseOrders/new/',
    path: '/purchaseOrders/new/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdPurchaseOrdersPurchaseIdIndexRoute =
  AuthenticatedProjectsProjectIdPurchaseOrdersPurchaseIdIndexRouteImport.update(
    {
      id: '/purchaseOrders/$purchaseId/',
      path: '/purchaseOrders/$purchaseId/',
      getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
    } as any,
  )
const AuthenticatedProjectsProjectIdPayslipNewIndexRoute =
  AuthenticatedProjectsProjectIdPayslipNewIndexRouteImport.update({
    id: '/payslip/new/',
    path: '/payslip/new/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdPayslipPayslipIdIndexRoute =
  AuthenticatedProjectsProjectIdPayslipPayslipIdIndexRouteImport.update({
    id: '/payslip/$PayslipId/',
    path: '/payslip/$PayslipId/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdExpensesNewIndexRoute =
  AuthenticatedProjectsProjectIdExpensesNewIndexRouteImport.update({
    id: '/expenses/new/',
    path: '/expenses/new/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdExpensesExpenseIdIndexRoute =
  AuthenticatedProjectsProjectIdExpensesExpenseIdIndexRouteImport.update({
    id: '/expenses/$ExpenseId/',
    path: '/expenses/$ExpenseId/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdEstimatesVariationsIndexRoute =
  AuthenticatedProjectsProjectIdEstimatesVariationsIndexRouteImport.update({
    id: '/estimates/variations/',
    path: '/estimates/variations/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdEstimatesEstimateIndexRoute =
  AuthenticatedProjectsProjectIdEstimatesEstimateIndexRouteImport.update({
    id: '/estimates/estimate/',
    path: '/estimates/estimate/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdWagesWageIdEditIndexRoute =
  AuthenticatedProjectsProjectIdWagesWageIdEditIndexRouteImport.update({
    id: '/wages/$WageId/edit/',
    path: '/wages/$WageId/edit/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdSubcontractorsWagesNewIndexRoute =
  AuthenticatedProjectsProjectIdSubcontractorsWagesNewIndexRouteImport.update({
    id: '/subcontractors/wages/new/',
    path: '/subcontractors/wages/new/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdSubcontractorsWagesWageIdIndexRoute =
  AuthenticatedProjectsProjectIdSubcontractorsWagesWageIdIndexRouteImport.update(
    {
      id: '/subcontractors/wages/$wageId/',
      path: '/subcontractors/wages/$wageId/',
      getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
    } as any,
  )
const AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersNewIndexRoute =
  AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersNewIndexRouteImport.update(
    {
      id: '/subcontractors/purchase-orders/new/',
      path: '/subcontractors/purchase-orders/new/',
      getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
    } as any,
  )
const AuthenticatedProjectsProjectIdSubcontractorsExpensesNewIndexRoute =
  AuthenticatedProjectsProjectIdSubcontractorsExpensesNewIndexRouteImport.update(
    {
      id: '/subcontractors/expenses/new/',
      path: '/subcontractors/expenses/new/',
      getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
    } as any,
  )
const AuthenticatedProjectsProjectIdSubcontractorsExpensesExpenseIdIndexRoute =
  AuthenticatedProjectsProjectIdSubcontractorsExpensesExpenseIdIndexRouteImport.update(
    {
      id: '/subcontractors/expenses/$expenseId/',
      path: '/subcontractors/expenses/$expenseId/',
      getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
    } as any,
  )
const AuthenticatedProjectsProjectIdPurchaseOrdersPurchaseIdEditIndexRoute =
  AuthenticatedProjectsProjectIdPurchaseOrdersPurchaseIdEditIndexRouteImport.update(
    {
      id: '/purchaseOrders/$purchaseId/edit/',
      path: '/purchaseOrders/$purchaseId/edit/',
      getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
    } as any,
  )
const AuthenticatedProjectsProjectIdPayslipPayslipIdEditIndexRoute =
  AuthenticatedProjectsProjectIdPayslipPayslipIdEditIndexRouteImport.update({
    id: '/payslip/$PayslipId/edit/',
    path: '/payslip/$PayslipId/edit/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdExpensesExpenseIdEditIndexRoute =
  AuthenticatedProjectsProjectIdExpensesExpenseIdEditIndexRouteImport.update({
    id: '/expenses/$ExpenseId/edit/',
    path: '/expenses/$ExpenseId/edit/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdEstimatesVariationsNewIndexRoute =
  AuthenticatedProjectsProjectIdEstimatesVariationsNewIndexRouteImport.update({
    id: '/estimates/variations/new/',
    path: '/estimates/variations/new/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdEstimatesVariationsVariationIdIndexRoute =
  AuthenticatedProjectsProjectIdEstimatesVariationsVariationIdIndexRouteImport.update(
    {
      id: '/estimates/variations/$variationId/',
      path: '/estimates/variations/$variationId/',
      getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
    } as any,
  )
const AuthenticatedProjectsProjectIdEstimatesEstimateNewIndexRoute =
  AuthenticatedProjectsProjectIdEstimatesEstimateNewIndexRouteImport.update({
    id: '/estimates/estimate/new/',
    path: '/estimates/estimate/new/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdSubcontractorsWagesWageIdEditIndexRoute =
  AuthenticatedProjectsProjectIdSubcontractorsWagesWageIdEditIndexRouteImport.update(
    {
      id: '/subcontractors/wages/$wageId/edit/',
      path: '/subcontractors/wages/$wageId/edit/',
      getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
    } as any,
  )
const AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersPurchaseIdEditIndexRoute =
  AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersPurchaseIdEditIndexRouteImport.update(
    {
      id: '/subcontractors/purchase-orders/$purchaseId/edit/',
      path: '/subcontractors/purchase-orders/$purchaseId/edit/',
      getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
    } as any,
  )
const AuthenticatedProjectsProjectIdSubcontractorsExpensesExpenseIdEditIndexRoute =
  AuthenticatedProjectsProjectIdSubcontractorsExpensesExpenseIdEditIndexRouteImport.update(
    {
      id: '/subcontractors/expenses/$expenseId/edit/',
      path: '/subcontractors/expenses/$expenseId/edit/',
      getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
    } as any,
  )
const AuthenticatedProjectsProjectIdEstimatesVariationsVariationIdEditIndexRoute =
  AuthenticatedProjectsProjectIdEstimatesVariationsVariationIdEditIndexRouteImport.update(
    {
      id: '/estimates/variations/$variationId/edit/',
      path: '/estimates/variations/$variationId/edit/',
      getParentRoute: () => AuthenticatedProjectsProjectIdRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/': typeof ClerkauthRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteRouteWithChildren
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/Clients': typeof AuthenticatedClientsIndexRoute
  '/Subcontractors': typeof AuthenticatedSubcontractorsIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/items': typeof AuthenticatedItemsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/vendors': typeof AuthenticatedVendorsIndexRoute
  '/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/projects/new': typeof AuthenticatedProjectsNewIndexRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdIndexRoute
  '/vendors/new': typeof AuthenticatedVendorsNewIndexRoute
  '/projects/$projectId/budget': typeof AuthenticatedProjectsProjectIdBudgetIndexRoute
  '/projects/$projectId/edit': typeof AuthenticatedProjectsProjectIdEditIndexRoute
  '/projects/$projectId/expenses': typeof AuthenticatedProjectsProjectIdExpensesIndexRoute
  '/projects/$projectId/payslip': typeof AuthenticatedProjectsProjectIdPayslipIndexRoute
  '/projects/$projectId/purchaseOrders': typeof AuthenticatedProjectsProjectIdPurchaseOrdersIndexRoute
  '/projects/$projectId/wages': typeof AuthenticatedProjectsProjectIdWagesIndexRoute
  '/projects/$projectId/estimates/estimate': typeof AuthenticatedProjectsProjectIdEstimatesEstimateIndexRoute
  '/projects/$projectId/estimates/variations': typeof AuthenticatedProjectsProjectIdEstimatesVariationsIndexRoute
  '/projects/$projectId/expenses/$ExpenseId': typeof AuthenticatedProjectsProjectIdExpensesExpenseIdIndexRoute
  '/projects/$projectId/expenses/new': typeof AuthenticatedProjectsProjectIdExpensesNewIndexRoute
  '/projects/$projectId/payslip/$PayslipId': typeof AuthenticatedProjectsProjectIdPayslipPayslipIdIndexRoute
  '/projects/$projectId/payslip/new': typeof AuthenticatedProjectsProjectIdPayslipNewIndexRoute
  '/projects/$projectId/purchaseOrders/$purchaseId': typeof AuthenticatedProjectsProjectIdPurchaseOrdersPurchaseIdIndexRoute
  '/projects/$projectId/purchaseOrders/new': typeof AuthenticatedProjectsProjectIdPurchaseOrdersNewIndexRoute
  '/projects/$projectId/subcontractors/expenses': typeof AuthenticatedProjectsProjectIdSubcontractorsExpensesIndexRoute
  '/projects/$projectId/subcontractors/purchase-orders': typeof AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersIndexRoute
  '/projects/$projectId/subcontractors/wages': typeof AuthenticatedProjectsProjectIdSubcontractorsWagesIndexRoute
  '/projects/$projectId/wages/$WageId': typeof AuthenticatedProjectsProjectIdWagesWageIdIndexRoute
  '/projects/$projectId/wages/new': typeof AuthenticatedProjectsProjectIdWagesNewIndexRoute
  '/projects/$projectId/estimates/estimate/new': typeof AuthenticatedProjectsProjectIdEstimatesEstimateNewIndexRoute
  '/projects/$projectId/estimates/variations/$variationId': typeof AuthenticatedProjectsProjectIdEstimatesVariationsVariationIdIndexRoute
  '/projects/$projectId/estimates/variations/new': typeof AuthenticatedProjectsProjectIdEstimatesVariationsNewIndexRoute
  '/projects/$projectId/expenses/$ExpenseId/edit': typeof AuthenticatedProjectsProjectIdExpensesExpenseIdEditIndexRoute
  '/projects/$projectId/payslip/$PayslipId/edit': typeof AuthenticatedProjectsProjectIdPayslipPayslipIdEditIndexRoute
  '/projects/$projectId/purchaseOrders/$purchaseId/edit': typeof AuthenticatedProjectsProjectIdPurchaseOrdersPurchaseIdEditIndexRoute
  '/projects/$projectId/subcontractors/expenses/$expenseId': typeof AuthenticatedProjectsProjectIdSubcontractorsExpensesExpenseIdIndexRoute
  '/projects/$projectId/subcontractors/expenses/new': typeof AuthenticatedProjectsProjectIdSubcontractorsExpensesNewIndexRoute
  '/projects/$projectId/subcontractors/purchase-orders/new': typeof AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersNewIndexRoute
  '/projects/$projectId/subcontractors/wages/$wageId': typeof AuthenticatedProjectsProjectIdSubcontractorsWagesWageIdIndexRoute
  '/projects/$projectId/subcontractors/wages/new': typeof AuthenticatedProjectsProjectIdSubcontractorsWagesNewIndexRoute
  '/projects/$projectId/wages/$WageId/edit': typeof AuthenticatedProjectsProjectIdWagesWageIdEditIndexRoute
  '/projects/$projectId/estimates/variations/$variationId/edit': typeof AuthenticatedProjectsProjectIdEstimatesVariationsVariationIdEditIndexRoute
  '/projects/$projectId/subcontractors/expenses/$expenseId/edit': typeof AuthenticatedProjectsProjectIdSubcontractorsExpensesExpenseIdEditIndexRoute
  '/projects/$projectId/subcontractors/purchase-orders/$purchaseId/edit': typeof AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersPurchaseIdEditIndexRoute
  '/projects/$projectId/subcontractors/wages/$wageId/edit': typeof AuthenticatedProjectsProjectIdSubcontractorsWagesWageIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/Clients': typeof AuthenticatedClientsIndexRoute
  '/Subcontractors': typeof AuthenticatedSubcontractorsIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/items': typeof AuthenticatedItemsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/vendors': typeof AuthenticatedVendorsIndexRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/projects/new': typeof AuthenticatedProjectsNewIndexRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdIndexRoute
  '/vendors/new': typeof AuthenticatedVendorsNewIndexRoute
  '/projects/$projectId/budget': typeof AuthenticatedProjectsProjectIdBudgetIndexRoute
  '/projects/$projectId/edit': typeof AuthenticatedProjectsProjectIdEditIndexRoute
  '/projects/$projectId/expenses': typeof AuthenticatedProjectsProjectIdExpensesIndexRoute
  '/projects/$projectId/payslip': typeof AuthenticatedProjectsProjectIdPayslipIndexRoute
  '/projects/$projectId/purchaseOrders': typeof AuthenticatedProjectsProjectIdPurchaseOrdersIndexRoute
  '/projects/$projectId/wages': typeof AuthenticatedProjectsProjectIdWagesIndexRoute
  '/projects/$projectId/estimates/estimate': typeof AuthenticatedProjectsProjectIdEstimatesEstimateIndexRoute
  '/projects/$projectId/estimates/variations': typeof AuthenticatedProjectsProjectIdEstimatesVariationsIndexRoute
  '/projects/$projectId/expenses/$ExpenseId': typeof AuthenticatedProjectsProjectIdExpensesExpenseIdIndexRoute
  '/projects/$projectId/expenses/new': typeof AuthenticatedProjectsProjectIdExpensesNewIndexRoute
  '/projects/$projectId/payslip/$PayslipId': typeof AuthenticatedProjectsProjectIdPayslipPayslipIdIndexRoute
  '/projects/$projectId/payslip/new': typeof AuthenticatedProjectsProjectIdPayslipNewIndexRoute
  '/projects/$projectId/purchaseOrders/$purchaseId': typeof AuthenticatedProjectsProjectIdPurchaseOrdersPurchaseIdIndexRoute
  '/projects/$projectId/purchaseOrders/new': typeof AuthenticatedProjectsProjectIdPurchaseOrdersNewIndexRoute
  '/projects/$projectId/subcontractors/expenses': typeof AuthenticatedProjectsProjectIdSubcontractorsExpensesIndexRoute
  '/projects/$projectId/subcontractors/purchase-orders': typeof AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersIndexRoute
  '/projects/$projectId/subcontractors/wages': typeof AuthenticatedProjectsProjectIdSubcontractorsWagesIndexRoute
  '/projects/$projectId/wages/$WageId': typeof AuthenticatedProjectsProjectIdWagesWageIdIndexRoute
  '/projects/$projectId/wages/new': typeof AuthenticatedProjectsProjectIdWagesNewIndexRoute
  '/projects/$projectId/estimates/estimate/new': typeof AuthenticatedProjectsProjectIdEstimatesEstimateNewIndexRoute
  '/projects/$projectId/estimates/variations/$variationId': typeof AuthenticatedProjectsProjectIdEstimatesVariationsVariationIdIndexRoute
  '/projects/$projectId/estimates/variations/new': typeof AuthenticatedProjectsProjectIdEstimatesVariationsNewIndexRoute
  '/projects/$projectId/expenses/$ExpenseId/edit': typeof AuthenticatedProjectsProjectIdExpensesExpenseIdEditIndexRoute
  '/projects/$projectId/payslip/$PayslipId/edit': typeof AuthenticatedProjectsProjectIdPayslipPayslipIdEditIndexRoute
  '/projects/$projectId/purchaseOrders/$purchaseId/edit': typeof AuthenticatedProjectsProjectIdPurchaseOrdersPurchaseIdEditIndexRoute
  '/projects/$projectId/subcontractors/expenses/$expenseId': typeof AuthenticatedProjectsProjectIdSubcontractorsExpensesExpenseIdIndexRoute
  '/projects/$projectId/subcontractors/expenses/new': typeof AuthenticatedProjectsProjectIdSubcontractorsExpensesNewIndexRoute
  '/projects/$projectId/subcontractors/purchase-orders/new': typeof AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersNewIndexRoute
  '/projects/$projectId/subcontractors/wages/$wageId': typeof AuthenticatedProjectsProjectIdSubcontractorsWagesWageIdIndexRoute
  '/projects/$projectId/subcontractors/wages/new': typeof AuthenticatedProjectsProjectIdSubcontractorsWagesNewIndexRoute
  '/projects/$projectId/wages/$WageId/edit': typeof AuthenticatedProjectsProjectIdWagesWageIdEditIndexRoute
  '/projects/$projectId/estimates/variations/$variationId/edit': typeof AuthenticatedProjectsProjectIdEstimatesVariationsVariationIdEditIndexRoute
  '/projects/$projectId/subcontractors/expenses/$expenseId/edit': typeof AuthenticatedProjectsProjectIdSubcontractorsExpensesExpenseIdEditIndexRoute
  '/projects/$projectId/subcontractors/purchase-orders/$purchaseId/edit': typeof AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersPurchaseIdEditIndexRoute
  '/projects/$projectId/subcontractors/wages/$wageId/edit': typeof AuthenticatedProjectsProjectIdSubcontractorsWagesWageIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteRouteWithChildren
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/Clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/Subcontractors/': typeof AuthenticatedSubcontractorsIndexRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/items/': typeof AuthenticatedItemsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/vendors/': typeof AuthenticatedVendorsIndexRoute
  '/_authenticated/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/_authenticated/projects/new/': typeof AuthenticatedProjectsNewIndexRoute
  '/_authenticated/users/$userId/': typeof AuthenticatedUsersUserIdIndexRoute
  '/_authenticated/vendors/new/': typeof AuthenticatedVendorsNewIndexRoute
  '/_authenticated/projects/$projectId/budget/': typeof AuthenticatedProjectsProjectIdBudgetIndexRoute
  '/_authenticated/projects/$projectId/edit/': typeof AuthenticatedProjectsProjectIdEditIndexRoute
  '/_authenticated/projects/$projectId/expenses/': typeof AuthenticatedProjectsProjectIdExpensesIndexRoute
  '/_authenticated/projects/$projectId/payslip/': typeof AuthenticatedProjectsProjectIdPayslipIndexRoute
  '/_authenticated/projects/$projectId/purchaseOrders/': typeof AuthenticatedProjectsProjectIdPurchaseOrdersIndexRoute
  '/_authenticated/projects/$projectId/wages/': typeof AuthenticatedProjectsProjectIdWagesIndexRoute
  '/_authenticated/projects/$projectId/estimates/estimate/': typeof AuthenticatedProjectsProjectIdEstimatesEstimateIndexRoute
  '/_authenticated/projects/$projectId/estimates/variations/': typeof AuthenticatedProjectsProjectIdEstimatesVariationsIndexRoute
  '/_authenticated/projects/$projectId/expenses/$ExpenseId/': typeof AuthenticatedProjectsProjectIdExpensesExpenseIdIndexRoute
  '/_authenticated/projects/$projectId/expenses/new/': typeof AuthenticatedProjectsProjectIdExpensesNewIndexRoute
  '/_authenticated/projects/$projectId/payslip/$PayslipId/': typeof AuthenticatedProjectsProjectIdPayslipPayslipIdIndexRoute
  '/_authenticated/projects/$projectId/payslip/new/': typeof AuthenticatedProjectsProjectIdPayslipNewIndexRoute
  '/_authenticated/projects/$projectId/purchaseOrders/$purchaseId/': typeof AuthenticatedProjectsProjectIdPurchaseOrdersPurchaseIdIndexRoute
  '/_authenticated/projects/$projectId/purchaseOrders/new/': typeof AuthenticatedProjectsProjectIdPurchaseOrdersNewIndexRoute
  '/_authenticated/projects/$projectId/subcontractors/expenses/': typeof AuthenticatedProjectsProjectIdSubcontractorsExpensesIndexRoute
  '/_authenticated/projects/$projectId/subcontractors/purchase-orders/': typeof AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersIndexRoute
  '/_authenticated/projects/$projectId/subcontractors/wages/': typeof AuthenticatedProjectsProjectIdSubcontractorsWagesIndexRoute
  '/_authenticated/projects/$projectId/wages/$WageId/': typeof AuthenticatedProjectsProjectIdWagesWageIdIndexRoute
  '/_authenticated/projects/$projectId/wages/new/': typeof AuthenticatedProjectsProjectIdWagesNewIndexRoute
  '/_authenticated/projects/$projectId/estimates/estimate/new/': typeof AuthenticatedProjectsProjectIdEstimatesEstimateNewIndexRoute
  '/_authenticated/projects/$projectId/estimates/variations/$variationId/': typeof AuthenticatedProjectsProjectIdEstimatesVariationsVariationIdIndexRoute
  '/_authenticated/projects/$projectId/estimates/variations/new/': typeof AuthenticatedProjectsProjectIdEstimatesVariationsNewIndexRoute
  '/_authenticated/projects/$projectId/expenses/$ExpenseId/edit/': typeof AuthenticatedProjectsProjectIdExpensesExpenseIdEditIndexRoute
  '/_authenticated/projects/$projectId/payslip/$PayslipId/edit/': typeof AuthenticatedProjectsProjectIdPayslipPayslipIdEditIndexRoute
  '/_authenticated/projects/$projectId/purchaseOrders/$purchaseId/edit/': typeof AuthenticatedProjectsProjectIdPurchaseOrdersPurchaseIdEditIndexRoute
  '/_authenticated/projects/$projectId/subcontractors/expenses/$expenseId/': typeof AuthenticatedProjectsProjectIdSubcontractorsExpensesExpenseIdIndexRoute
  '/_authenticated/projects/$projectId/subcontractors/expenses/new/': typeof AuthenticatedProjectsProjectIdSubcontractorsExpensesNewIndexRoute
  '/_authenticated/projects/$projectId/subcontractors/purchase-orders/new/': typeof AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersNewIndexRoute
  '/_authenticated/projects/$projectId/subcontractors/wages/$wageId/': typeof AuthenticatedProjectsProjectIdSubcontractorsWagesWageIdIndexRoute
  '/_authenticated/projects/$projectId/subcontractors/wages/new/': typeof AuthenticatedProjectsProjectIdSubcontractorsWagesNewIndexRoute
  '/_authenticated/projects/$projectId/wages/$WageId/edit/': typeof AuthenticatedProjectsProjectIdWagesWageIdEditIndexRoute
  '/_authenticated/projects/$projectId/estimates/variations/$variationId/edit/': typeof AuthenticatedProjectsProjectIdEstimatesVariationsVariationIdEditIndexRoute
  '/_authenticated/projects/$projectId/subcontractors/expenses/$expenseId/edit/': typeof AuthenticatedProjectsProjectIdSubcontractorsExpensesExpenseIdEditIndexRoute
  '/_authenticated/projects/$projectId/subcontractors/purchase-orders/$purchaseId/edit/': typeof AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersPurchaseIdEditIndexRoute
  '/_authenticated/projects/$projectId/subcontractors/wages/$wageId/edit/': typeof AuthenticatedProjectsProjectIdSubcontractorsWagesWageIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/clerk'
    | '/settings'
    | '/clerk/'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/projects/$projectId'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/Clients'
    | '/Subcontractors'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/items'
    | '/settings/'
    | '/tasks'
    | '/users'
    | '/vendors'
    | '/projects/$projectId/'
    | '/projects/new'
    | '/users/$userId'
    | '/vendors/new'
    | '/projects/$projectId/budget'
    | '/projects/$projectId/edit'
    | '/projects/$projectId/expenses'
    | '/projects/$projectId/payslip'
    | '/projects/$projectId/purchaseOrders'
    | '/projects/$projectId/wages'
    | '/projects/$projectId/estimates/estimate'
    | '/projects/$projectId/estimates/variations'
    | '/projects/$projectId/expenses/$ExpenseId'
    | '/projects/$projectId/expenses/new'
    | '/projects/$projectId/payslip/$PayslipId'
    | '/projects/$projectId/payslip/new'
    | '/projects/$projectId/purchaseOrders/$purchaseId'
    | '/projects/$projectId/purchaseOrders/new'
    | '/projects/$projectId/subcontractors/expenses'
    | '/projects/$projectId/subcontractors/purchase-orders'
    | '/projects/$projectId/subcontractors/wages'
    | '/projects/$projectId/wages/$WageId'
    | '/projects/$projectId/wages/new'
    | '/projects/$projectId/estimates/estimate/new'
    | '/projects/$projectId/estimates/variations/$variationId'
    | '/projects/$projectId/estimates/variations/new'
    | '/projects/$projectId/expenses/$ExpenseId/edit'
    | '/projects/$projectId/payslip/$PayslipId/edit'
    | '/projects/$projectId/purchaseOrders/$purchaseId/edit'
    | '/projects/$projectId/subcontractors/expenses/$expenseId'
    | '/projects/$projectId/subcontractors/expenses/new'
    | '/projects/$projectId/subcontractors/purchase-orders/new'
    | '/projects/$projectId/subcontractors/wages/$wageId'
    | '/projects/$projectId/subcontractors/wages/new'
    | '/projects/$projectId/wages/$WageId/edit'
    | '/projects/$projectId/estimates/variations/$variationId/edit'
    | '/projects/$projectId/subcontractors/expenses/$expenseId/edit'
    | '/projects/$projectId/subcontractors/purchase-orders/$purchaseId/edit'
    | '/projects/$projectId/subcontractors/wages/$wageId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/Clients'
    | '/Subcontractors'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/items'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/vendors'
    | '/projects/$projectId'
    | '/projects/new'
    | '/users/$userId'
    | '/vendors/new'
    | '/projects/$projectId/budget'
    | '/projects/$projectId/edit'
    | '/projects/$projectId/expenses'
    | '/projects/$projectId/payslip'
    | '/projects/$projectId/purchaseOrders'
    | '/projects/$projectId/wages'
    | '/projects/$projectId/estimates/estimate'
    | '/projects/$projectId/estimates/variations'
    | '/projects/$projectId/expenses/$ExpenseId'
    | '/projects/$projectId/expenses/new'
    | '/projects/$projectId/payslip/$PayslipId'
    | '/projects/$projectId/payslip/new'
    | '/projects/$projectId/purchaseOrders/$purchaseId'
    | '/projects/$projectId/purchaseOrders/new'
    | '/projects/$projectId/subcontractors/expenses'
    | '/projects/$projectId/subcontractors/purchase-orders'
    | '/projects/$projectId/subcontractors/wages'
    | '/projects/$projectId/wages/$WageId'
    | '/projects/$projectId/wages/new'
    | '/projects/$projectId/estimates/estimate/new'
    | '/projects/$projectId/estimates/variations/$variationId'
    | '/projects/$projectId/estimates/variations/new'
    | '/projects/$projectId/expenses/$ExpenseId/edit'
    | '/projects/$projectId/payslip/$PayslipId/edit'
    | '/projects/$projectId/purchaseOrders/$purchaseId/edit'
    | '/projects/$projectId/subcontractors/expenses/$expenseId'
    | '/projects/$projectId/subcontractors/expenses/new'
    | '/projects/$projectId/subcontractors/purchase-orders/new'
    | '/projects/$projectId/subcontractors/wages/$wageId'
    | '/projects/$projectId/subcontractors/wages/new'
    | '/projects/$projectId/wages/$WageId/edit'
    | '/projects/$projectId/estimates/variations/$variationId/edit'
    | '/projects/$projectId/subcontractors/expenses/$expenseId/edit'
    | '/projects/$projectId/subcontractors/purchase-orders/$purchaseId/edit'
    | '/projects/$projectId/subcontractors/wages/$wageId/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/Clients/'
    | '/_authenticated/Subcontractors/'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/help-center/'
    | '/_authenticated/items/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/vendors/'
    | '/_authenticated/projects/$projectId/'
    | '/_authenticated/projects/new/'
    | '/_authenticated/users/$userId/'
    | '/_authenticated/vendors/new/'
    | '/_authenticated/projects/$projectId/budget/'
    | '/_authenticated/projects/$projectId/edit/'
    | '/_authenticated/projects/$projectId/expenses/'
    | '/_authenticated/projects/$projectId/payslip/'
    | '/_authenticated/projects/$projectId/purchaseOrders/'
    | '/_authenticated/projects/$projectId/wages/'
    | '/_authenticated/projects/$projectId/estimates/estimate/'
    | '/_authenticated/projects/$projectId/estimates/variations/'
    | '/_authenticated/projects/$projectId/expenses/$ExpenseId/'
    | '/_authenticated/projects/$projectId/expenses/new/'
    | '/_authenticated/projects/$projectId/payslip/$PayslipId/'
    | '/_authenticated/projects/$projectId/payslip/new/'
    | '/_authenticated/projects/$projectId/purchaseOrders/$purchaseId/'
    | '/_authenticated/projects/$projectId/purchaseOrders/new/'
    | '/_authenticated/projects/$projectId/subcontractors/expenses/'
    | '/_authenticated/projects/$projectId/subcontractors/purchase-orders/'
    | '/_authenticated/projects/$projectId/subcontractors/wages/'
    | '/_authenticated/projects/$projectId/wages/$WageId/'
    | '/_authenticated/projects/$projectId/wages/new/'
    | '/_authenticated/projects/$projectId/estimates/estimate/new/'
    | '/_authenticated/projects/$projectId/estimates/variations/$variationId/'
    | '/_authenticated/projects/$projectId/estimates/variations/new/'
    | '/_authenticated/projects/$projectId/expenses/$ExpenseId/edit/'
    | '/_authenticated/projects/$projectId/payslip/$PayslipId/edit/'
    | '/_authenticated/projects/$projectId/purchaseOrders/$purchaseId/edit/'
    | '/_authenticated/projects/$projectId/subcontractors/expenses/$expenseId/'
    | '/_authenticated/projects/$projectId/subcontractors/expenses/new/'
    | '/_authenticated/projects/$projectId/subcontractors/purchase-orders/new/'
    | '/_authenticated/projects/$projectId/subcontractors/wages/$wageId/'
    | '/_authenticated/projects/$projectId/subcontractors/wages/new/'
    | '/_authenticated/projects/$projectId/wages/$WageId/edit/'
    | '/_authenticated/projects/$projectId/estimates/variations/$variationId/edit/'
    | '/_authenticated/projects/$projectId/subcontractors/expenses/$expenseId/edit/'
    | '/_authenticated/projects/$projectId/subcontractors/purchase-orders/$purchaseId/edit/'
    | '/_authenticated/projects/$projectId/subcontractors/wages/$wageId/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: '/'
      fullPath: '/clerk/'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendors/': {
      id: '/_authenticated/vendors/'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AuthenticatedVendorsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/items/': {
      id: '/_authenticated/items/'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof AuthenticatedItemsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/Subcontractors/': {
      id: '/_authenticated/Subcontractors/'
      path: '/Subcontractors'
      fullPath: '/Subcontractors'
      preLoaderRoute: typeof AuthenticatedSubcontractorsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/Clients/': {
      id: '/_authenticated/Clients/'
      path: '/Clients'
      fullPath: '/Clients'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendors/new/': {
      id: '/_authenticated/vendors/new/'
      path: '/vendors/new'
      fullPath: '/vendors/new'
      preLoaderRoute: typeof AuthenticatedVendorsNewIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/$userId/': {
      id: '/_authenticated/users/$userId/'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthenticatedUsersUserIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/new/': {
      id: '/_authenticated/projects/new/'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthenticatedProjectsNewIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/': {
      id: '/_authenticated/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/wages/': {
      id: '/_authenticated/projects/$projectId/wages/'
      path: '/wages'
      fullPath: '/projects/$projectId/wages'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdWagesIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/purchaseOrders/': {
      id: '/_authenticated/projects/$projectId/purchaseOrders/'
      path: '/purchaseOrders'
      fullPath: '/projects/$projectId/purchaseOrders'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdPurchaseOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/payslip/': {
      id: '/_authenticated/projects/$projectId/payslip/'
      path: '/payslip'
      fullPath: '/projects/$projectId/payslip'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdPayslipIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/expenses/': {
      id: '/_authenticated/projects/$projectId/expenses/'
      path: '/expenses'
      fullPath: '/projects/$projectId/expenses'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdExpensesIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/edit/': {
      id: '/_authenticated/projects/$projectId/edit/'
      path: '/edit'
      fullPath: '/projects/$projectId/edit'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdEditIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/budget/': {
      id: '/_authenticated/projects/$projectId/budget/'
      path: '/budget'
      fullPath: '/projects/$projectId/budget'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdBudgetIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/wages/new/': {
      id: '/_authenticated/projects/$projectId/wages/new/'
      path: '/wages/new'
      fullPath: '/projects/$projectId/wages/new'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdWagesNewIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/wages/$WageId/': {
      id: '/_authenticated/projects/$projectId/wages/$WageId/'
      path: '/wages/$WageId'
      fullPath: '/projects/$projectId/wages/$WageId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdWagesWageIdIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/subcontractors/wages/': {
      id: '/_authenticated/projects/$projectId/subcontractors/wages/'
      path: '/subcontractors/wages'
      fullPath: '/projects/$projectId/subcontractors/wages'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSubcontractorsWagesIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/subcontractors/purchase-orders/': {
      id: '/_authenticated/projects/$projectId/subcontractors/purchase-orders/'
      path: '/subcontractors/purchase-orders'
      fullPath: '/projects/$projectId/subcontractors/purchase-orders'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/subcontractors/expenses/': {
      id: '/_authenticated/projects/$projectId/subcontractors/expenses/'
      path: '/subcontractors/expenses'
      fullPath: '/projects/$projectId/subcontractors/expenses'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSubcontractorsExpensesIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/purchaseOrders/new/': {
      id: '/_authenticated/projects/$projectId/purchaseOrders/new/'
      path: '/purchaseOrders/new'
      fullPath: '/projects/$projectId/purchaseOrders/new'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdPurchaseOrdersNewIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/purchaseOrders/$purchaseId/': {
      id: '/_authenticated/projects/$projectId/purchaseOrders/$purchaseId/'
      path: '/purchaseOrders/$purchaseId'
      fullPath: '/projects/$projectId/purchaseOrders/$purchaseId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdPurchaseOrdersPurchaseIdIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/payslip/new/': {
      id: '/_authenticated/projects/$projectId/payslip/new/'
      path: '/payslip/new'
      fullPath: '/projects/$projectId/payslip/new'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdPayslipNewIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/payslip/$PayslipId/': {
      id: '/_authenticated/projects/$projectId/payslip/$PayslipId/'
      path: '/payslip/$PayslipId'
      fullPath: '/projects/$projectId/payslip/$PayslipId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdPayslipPayslipIdIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/expenses/new/': {
      id: '/_authenticated/projects/$projectId/expenses/new/'
      path: '/expenses/new'
      fullPath: '/projects/$projectId/expenses/new'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdExpensesNewIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/expenses/$ExpenseId/': {
      id: '/_authenticated/projects/$projectId/expenses/$ExpenseId/'
      path: '/expenses/$ExpenseId'
      fullPath: '/projects/$projectId/expenses/$ExpenseId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdExpensesExpenseIdIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/estimates/variations/': {
      id: '/_authenticated/projects/$projectId/estimates/variations/'
      path: '/estimates/variations'
      fullPath: '/projects/$projectId/estimates/variations'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdEstimatesVariationsIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/estimates/estimate/': {
      id: '/_authenticated/projects/$projectId/estimates/estimate/'
      path: '/estimates/estimate'
      fullPath: '/projects/$projectId/estimates/estimate'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdEstimatesEstimateIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/wages/$WageId/edit/': {
      id: '/_authenticated/projects/$projectId/wages/$WageId/edit/'
      path: '/wages/$WageId/edit'
      fullPath: '/projects/$projectId/wages/$WageId/edit'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdWagesWageIdEditIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/subcontractors/wages/new/': {
      id: '/_authenticated/projects/$projectId/subcontractors/wages/new/'
      path: '/subcontractors/wages/new'
      fullPath: '/projects/$projectId/subcontractors/wages/new'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSubcontractorsWagesNewIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/subcontractors/wages/$wageId/': {
      id: '/_authenticated/projects/$projectId/subcontractors/wages/$wageId/'
      path: '/subcontractors/wages/$wageId'
      fullPath: '/projects/$projectId/subcontractors/wages/$wageId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSubcontractorsWagesWageIdIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/subcontractors/purchase-orders/new/': {
      id: '/_authenticated/projects/$projectId/subcontractors/purchase-orders/new/'
      path: '/subcontractors/purchase-orders/new'
      fullPath: '/projects/$projectId/subcontractors/purchase-orders/new'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersNewIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/subcontractors/expenses/new/': {
      id: '/_authenticated/projects/$projectId/subcontractors/expenses/new/'
      path: '/subcontractors/expenses/new'
      fullPath: '/projects/$projectId/subcontractors/expenses/new'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSubcontractorsExpensesNewIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/subcontractors/expenses/$expenseId/': {
      id: '/_authenticated/projects/$projectId/subcontractors/expenses/$expenseId/'
      path: '/subcontractors/expenses/$expenseId'
      fullPath: '/projects/$projectId/subcontractors/expenses/$expenseId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSubcontractorsExpensesExpenseIdIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/purchaseOrders/$purchaseId/edit/': {
      id: '/_authenticated/projects/$projectId/purchaseOrders/$purchaseId/edit/'
      path: '/purchaseOrders/$purchaseId/edit'
      fullPath: '/projects/$projectId/purchaseOrders/$purchaseId/edit'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdPurchaseOrdersPurchaseIdEditIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/payslip/$PayslipId/edit/': {
      id: '/_authenticated/projects/$projectId/payslip/$PayslipId/edit/'
      path: '/payslip/$PayslipId/edit'
      fullPath: '/projects/$projectId/payslip/$PayslipId/edit'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdPayslipPayslipIdEditIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/expenses/$ExpenseId/edit/': {
      id: '/_authenticated/projects/$projectId/expenses/$ExpenseId/edit/'
      path: '/expenses/$ExpenseId/edit'
      fullPath: '/projects/$projectId/expenses/$ExpenseId/edit'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdExpensesExpenseIdEditIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/estimates/variations/new/': {
      id: '/_authenticated/projects/$projectId/estimates/variations/new/'
      path: '/estimates/variations/new'
      fullPath: '/projects/$projectId/estimates/variations/new'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdEstimatesVariationsNewIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/estimates/variations/$variationId/': {
      id: '/_authenticated/projects/$projectId/estimates/variations/$variationId/'
      path: '/estimates/variations/$variationId'
      fullPath: '/projects/$projectId/estimates/variations/$variationId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdEstimatesVariationsVariationIdIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/estimates/estimate/new/': {
      id: '/_authenticated/projects/$projectId/estimates/estimate/new/'
      path: '/estimates/estimate/new'
      fullPath: '/projects/$projectId/estimates/estimate/new'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdEstimatesEstimateNewIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/subcontractors/wages/$wageId/edit/': {
      id: '/_authenticated/projects/$projectId/subcontractors/wages/$wageId/edit/'
      path: '/subcontractors/wages/$wageId/edit'
      fullPath: '/projects/$projectId/subcontractors/wages/$wageId/edit'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSubcontractorsWagesWageIdEditIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/subcontractors/purchase-orders/$purchaseId/edit/': {
      id: '/_authenticated/projects/$projectId/subcontractors/purchase-orders/$purchaseId/edit/'
      path: '/subcontractors/purchase-orders/$purchaseId/edit'
      fullPath: '/projects/$projectId/subcontractors/purchase-orders/$purchaseId/edit'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersPurchaseIdEditIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/subcontractors/expenses/$expenseId/edit/': {
      id: '/_authenticated/projects/$projectId/subcontractors/expenses/$expenseId/edit/'
      path: '/subcontractors/expenses/$expenseId/edit'
      fullPath: '/projects/$projectId/subcontractors/expenses/$expenseId/edit'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSubcontractorsExpensesExpenseIdEditIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
    '/_authenticated/projects/$projectId/estimates/variations/$variationId/edit/': {
      id: '/_authenticated/projects/$projectId/estimates/variations/$variationId/edit/'
      path: '/estimates/variations/$variationId/edit'
      fullPath: '/projects/$projectId/estimates/variations/$variationId/edit'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdEstimatesVariationsVariationIdEditIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedProjectsProjectIdRouteRouteChildren {
  AuthenticatedProjectsProjectIdIndexRoute: typeof AuthenticatedProjectsProjectIdIndexRoute
  AuthenticatedProjectsProjectIdBudgetIndexRoute: typeof AuthenticatedProjectsProjectIdBudgetIndexRoute
  AuthenticatedProjectsProjectIdEditIndexRoute: typeof AuthenticatedProjectsProjectIdEditIndexRoute
  AuthenticatedProjectsProjectIdExpensesIndexRoute: typeof AuthenticatedProjectsProjectIdExpensesIndexRoute
  AuthenticatedProjectsProjectIdPayslipIndexRoute: typeof AuthenticatedProjectsProjectIdPayslipIndexRoute
  AuthenticatedProjectsProjectIdPurchaseOrdersIndexRoute: typeof AuthenticatedProjectsProjectIdPurchaseOrdersIndexRoute
  AuthenticatedProjectsProjectIdWagesIndexRoute: typeof AuthenticatedProjectsProjectIdWagesIndexRoute
  AuthenticatedProjectsProjectIdEstimatesEstimateIndexRoute: typeof AuthenticatedProjectsProjectIdEstimatesEstimateIndexRoute
  AuthenticatedProjectsProjectIdEstimatesVariationsIndexRoute: typeof AuthenticatedProjectsProjectIdEstimatesVariationsIndexRoute
  AuthenticatedProjectsProjectIdExpensesExpenseIdIndexRoute: typeof AuthenticatedProjectsProjectIdExpensesExpenseIdIndexRoute
  AuthenticatedProjectsProjectIdExpensesNewIndexRoute: typeof AuthenticatedProjectsProjectIdExpensesNewIndexRoute
  AuthenticatedProjectsProjectIdPayslipPayslipIdIndexRoute: typeof AuthenticatedProjectsProjectIdPayslipPayslipIdIndexRoute
  AuthenticatedProjectsProjectIdPayslipNewIndexRoute: typeof AuthenticatedProjectsProjectIdPayslipNewIndexRoute
  AuthenticatedProjectsProjectIdPurchaseOrdersPurchaseIdIndexRoute: typeof AuthenticatedProjectsProjectIdPurchaseOrdersPurchaseIdIndexRoute
  AuthenticatedProjectsProjectIdPurchaseOrdersNewIndexRoute: typeof AuthenticatedProjectsProjectIdPurchaseOrdersNewIndexRoute
  AuthenticatedProjectsProjectIdSubcontractorsExpensesIndexRoute: typeof AuthenticatedProjectsProjectIdSubcontractorsExpensesIndexRoute
  AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersIndexRoute: typeof AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersIndexRoute
  AuthenticatedProjectsProjectIdSubcontractorsWagesIndexRoute: typeof AuthenticatedProjectsProjectIdSubcontractorsWagesIndexRoute
  AuthenticatedProjectsProjectIdWagesWageIdIndexRoute: typeof AuthenticatedProjectsProjectIdWagesWageIdIndexRoute
  AuthenticatedProjectsProjectIdWagesNewIndexRoute: typeof AuthenticatedProjectsProjectIdWagesNewIndexRoute
  AuthenticatedProjectsProjectIdEstimatesEstimateNewIndexRoute: typeof AuthenticatedProjectsProjectIdEstimatesEstimateNewIndexRoute
  AuthenticatedProjectsProjectIdEstimatesVariationsVariationIdIndexRoute: typeof AuthenticatedProjectsProjectIdEstimatesVariationsVariationIdIndexRoute
  AuthenticatedProjectsProjectIdEstimatesVariationsNewIndexRoute: typeof AuthenticatedProjectsProjectIdEstimatesVariationsNewIndexRoute
  AuthenticatedProjectsProjectIdExpensesExpenseIdEditIndexRoute: typeof AuthenticatedProjectsProjectIdExpensesExpenseIdEditIndexRoute
  AuthenticatedProjectsProjectIdPayslipPayslipIdEditIndexRoute: typeof AuthenticatedProjectsProjectIdPayslipPayslipIdEditIndexRoute
  AuthenticatedProjectsProjectIdPurchaseOrdersPurchaseIdEditIndexRoute: typeof AuthenticatedProjectsProjectIdPurchaseOrdersPurchaseIdEditIndexRoute
  AuthenticatedProjectsProjectIdSubcontractorsExpensesExpenseIdIndexRoute: typeof AuthenticatedProjectsProjectIdSubcontractorsExpensesExpenseIdIndexRoute
  AuthenticatedProjectsProjectIdSubcontractorsExpensesNewIndexRoute: typeof AuthenticatedProjectsProjectIdSubcontractorsExpensesNewIndexRoute
  AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersNewIndexRoute: typeof AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersNewIndexRoute
  AuthenticatedProjectsProjectIdSubcontractorsWagesWageIdIndexRoute: typeof AuthenticatedProjectsProjectIdSubcontractorsWagesWageIdIndexRoute
  AuthenticatedProjectsProjectIdSubcontractorsWagesNewIndexRoute: typeof AuthenticatedProjectsProjectIdSubcontractorsWagesNewIndexRoute
  AuthenticatedProjectsProjectIdWagesWageIdEditIndexRoute: typeof AuthenticatedProjectsProjectIdWagesWageIdEditIndexRoute
  AuthenticatedProjectsProjectIdEstimatesVariationsVariationIdEditIndexRoute: typeof AuthenticatedProjectsProjectIdEstimatesVariationsVariationIdEditIndexRoute
  AuthenticatedProjectsProjectIdSubcontractorsExpensesExpenseIdEditIndexRoute: typeof AuthenticatedProjectsProjectIdSubcontractorsExpensesExpenseIdEditIndexRoute
  AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersPurchaseIdEditIndexRoute: typeof AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersPurchaseIdEditIndexRoute
  AuthenticatedProjectsProjectIdSubcontractorsWagesWageIdEditIndexRoute: typeof AuthenticatedProjectsProjectIdSubcontractorsWagesWageIdEditIndexRoute
}

const AuthenticatedProjectsProjectIdRouteRouteChildren: AuthenticatedProjectsProjectIdRouteRouteChildren =
  {
    AuthenticatedProjectsProjectIdIndexRoute:
      AuthenticatedProjectsProjectIdIndexRoute,
    AuthenticatedProjectsProjectIdBudgetIndexRoute:
      AuthenticatedProjectsProjectIdBudgetIndexRoute,
    AuthenticatedProjectsProjectIdEditIndexRoute:
      AuthenticatedProjectsProjectIdEditIndexRoute,
    AuthenticatedProjectsProjectIdExpensesIndexRoute:
      AuthenticatedProjectsProjectIdExpensesIndexRoute,
    AuthenticatedProjectsProjectIdPayslipIndexRoute:
      AuthenticatedProjectsProjectIdPayslipIndexRoute,
    AuthenticatedProjectsProjectIdPurchaseOrdersIndexRoute:
      AuthenticatedProjectsProjectIdPurchaseOrdersIndexRoute,
    AuthenticatedProjectsProjectIdWagesIndexRoute:
      AuthenticatedProjectsProjectIdWagesIndexRoute,
    AuthenticatedProjectsProjectIdEstimatesEstimateIndexRoute:
      AuthenticatedProjectsProjectIdEstimatesEstimateIndexRoute,
    AuthenticatedProjectsProjectIdEstimatesVariationsIndexRoute:
      AuthenticatedProjectsProjectIdEstimatesVariationsIndexRoute,
    AuthenticatedProjectsProjectIdExpensesExpenseIdIndexRoute:
      AuthenticatedProjectsProjectIdExpensesExpenseIdIndexRoute,
    AuthenticatedProjectsProjectIdExpensesNewIndexRoute:
      AuthenticatedProjectsProjectIdExpensesNewIndexRoute,
    AuthenticatedProjectsProjectIdPayslipPayslipIdIndexRoute:
      AuthenticatedProjectsProjectIdPayslipPayslipIdIndexRoute,
    AuthenticatedProjectsProjectIdPayslipNewIndexRoute:
      AuthenticatedProjectsProjectIdPayslipNewIndexRoute,
    AuthenticatedProjectsProjectIdPurchaseOrdersPurchaseIdIndexRoute:
      AuthenticatedProjectsProjectIdPurchaseOrdersPurchaseIdIndexRoute,
    AuthenticatedProjectsProjectIdPurchaseOrdersNewIndexRoute:
      AuthenticatedProjectsProjectIdPurchaseOrdersNewIndexRoute,
    AuthenticatedProjectsProjectIdSubcontractorsExpensesIndexRoute:
      AuthenticatedProjectsProjectIdSubcontractorsExpensesIndexRoute,
    AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersIndexRoute:
      AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersIndexRoute,
    AuthenticatedProjectsProjectIdSubcontractorsWagesIndexRoute:
      AuthenticatedProjectsProjectIdSubcontractorsWagesIndexRoute,
    AuthenticatedProjectsProjectIdWagesWageIdIndexRoute:
      AuthenticatedProjectsProjectIdWagesWageIdIndexRoute,
    AuthenticatedProjectsProjectIdWagesNewIndexRoute:
      AuthenticatedProjectsProjectIdWagesNewIndexRoute,
    AuthenticatedProjectsProjectIdEstimatesEstimateNewIndexRoute:
      AuthenticatedProjectsProjectIdEstimatesEstimateNewIndexRoute,
    AuthenticatedProjectsProjectIdEstimatesVariationsVariationIdIndexRoute:
      AuthenticatedProjectsProjectIdEstimatesVariationsVariationIdIndexRoute,
    AuthenticatedProjectsProjectIdEstimatesVariationsNewIndexRoute:
      AuthenticatedProjectsProjectIdEstimatesVariationsNewIndexRoute,
    AuthenticatedProjectsProjectIdExpensesExpenseIdEditIndexRoute:
      AuthenticatedProjectsProjectIdExpensesExpenseIdEditIndexRoute,
    AuthenticatedProjectsProjectIdPayslipPayslipIdEditIndexRoute:
      AuthenticatedProjectsProjectIdPayslipPayslipIdEditIndexRoute,
    AuthenticatedProjectsProjectIdPurchaseOrdersPurchaseIdEditIndexRoute:
      AuthenticatedProjectsProjectIdPurchaseOrdersPurchaseIdEditIndexRoute,
    AuthenticatedProjectsProjectIdSubcontractorsExpensesExpenseIdIndexRoute:
      AuthenticatedProjectsProjectIdSubcontractorsExpensesExpenseIdIndexRoute,
    AuthenticatedProjectsProjectIdSubcontractorsExpensesNewIndexRoute:
      AuthenticatedProjectsProjectIdSubcontractorsExpensesNewIndexRoute,
    AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersNewIndexRoute:
      AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersNewIndexRoute,
    AuthenticatedProjectsProjectIdSubcontractorsWagesWageIdIndexRoute:
      AuthenticatedProjectsProjectIdSubcontractorsWagesWageIdIndexRoute,
    AuthenticatedProjectsProjectIdSubcontractorsWagesNewIndexRoute:
      AuthenticatedProjectsProjectIdSubcontractorsWagesNewIndexRoute,
    AuthenticatedProjectsProjectIdWagesWageIdEditIndexRoute:
      AuthenticatedProjectsProjectIdWagesWageIdEditIndexRoute,
    AuthenticatedProjectsProjectIdEstimatesVariationsVariationIdEditIndexRoute:
      AuthenticatedProjectsProjectIdEstimatesVariationsVariationIdEditIndexRoute,
    AuthenticatedProjectsProjectIdSubcontractorsExpensesExpenseIdEditIndexRoute:
      AuthenticatedProjectsProjectIdSubcontractorsExpensesExpenseIdEditIndexRoute,
    AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersPurchaseIdEditIndexRoute:
      AuthenticatedProjectsProjectIdSubcontractorsPurchaseOrdersPurchaseIdEditIndexRoute,
    AuthenticatedProjectsProjectIdSubcontractorsWagesWageIdEditIndexRoute:
      AuthenticatedProjectsProjectIdSubcontractorsWagesWageIdEditIndexRoute,
  }

const AuthenticatedProjectsProjectIdRouteRouteWithChildren =
  AuthenticatedProjectsProjectIdRouteRoute._addFileChildren(
    AuthenticatedProjectsProjectIdRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedProjectsProjectIdRouteRoute: typeof AuthenticatedProjectsProjectIdRouteRouteWithChildren
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedSubcontractorsIndexRoute: typeof AuthenticatedSubcontractorsIndexRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedItemsIndexRoute: typeof AuthenticatedItemsIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedVendorsIndexRoute: typeof AuthenticatedVendorsIndexRoute
  AuthenticatedProjectsNewIndexRoute: typeof AuthenticatedProjectsNewIndexRoute
  AuthenticatedUsersUserIdIndexRoute: typeof AuthenticatedUsersUserIdIndexRoute
  AuthenticatedVendorsNewIndexRoute: typeof AuthenticatedVendorsNewIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProjectsProjectIdRouteRoute:
    AuthenticatedProjectsProjectIdRouteRouteWithChildren,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedSubcontractorsIndexRoute: AuthenticatedSubcontractorsIndexRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedItemsIndexRoute: AuthenticatedItemsIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedVendorsIndexRoute: AuthenticatedVendorsIndexRoute,
  AuthenticatedProjectsNewIndexRoute: AuthenticatedProjectsNewIndexRoute,
  AuthenticatedUsersUserIdIndexRoute: AuthenticatedUsersUserIdIndexRoute,
  AuthenticatedVendorsNewIndexRoute: AuthenticatedVendorsNewIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
